import type { WorkspaceSnapshot } from "../types/workspace";

export const workspaceFixture: WorkspaceSnapshot = {
  sessionId: "session-v4",
  mode: "develop",
  rulebook: {
    name: "Accelerated London",
    version: 4,
    path: "flows/london.toml",
    side: "white",
    openingTags: [{ eco: "D00", name: "Queen's Pawn Game: Accelerated London System" }],
    warnings: [],
  },
  position: {
    fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
    historySan: [],
    turn: "white",
    legalMovesUci: ["d2d4", "e2e4", "g1f3"],
    lastMoveUci: null,
    gameOver: null,
  },
  decision: {
    status: "ready",
    source: "development",
    moveUci: "d2d4",
    moveSan: "d4",
    instructionRef: "d-pawn.develop",
    why: "Claim the center.",
    frontier: null,
    trace: ["Development d-pawn.develop: selected."],
  },
  pieceScripts: [
    {
      alias: "d-pawn",
      ref: "piece:white:pawn:d",
      label: "White d-pawn",
      currentSquare: "d2",
      mechanicalState: "undeveloped",
      authorable: true,
      development: {
        reference: "d-pawn.develop",
        to: "d4",
        requires: [],
        when: null,
        why: "Claim the center.",
        status: "selected",
        explanation: "First legal instruction.",
        condition: null,
      },
      interrupts: [
        {
          reference: "d-pawn.take-bishop",
          id: "take-bishop",
          requires: ["d-pawn.develop"],
          afterSan: null,
          when: null,
          required: false,
          attempts: [{ kind: "capture-type", value: "bishop", status: "failed", candidates: [], reason: "No bishop." }],
          why: "Capture a bishop when possible.",
          status: "no-action",
          explanation: "No action resolves.",
          trigger: null,
        },
      ],
      relationships: {
        attacks: [],
        attackers: [
          { piece: "black:b4", alias: "black-b-pawn", moveUci: "b4c3" },
          { piece: "black:d4", alias: "black-d-pawn", moveUci: "d4c3" },
        ],
        defendersByAttacker: [
          {
            attacker: "black:b4",
            attackerAlias: "black-b-pawn",
            defenders: [{ piece: "white:d2", alias: "d-pawn", moveUci: "d2c3" }],
          },
        ],
        distinctDefenders: ["white:d2"],
        attackerCount: 2,
        defenderCount: 1,
        attackBalance: 1,
        attacked: true,
        undefended: false,
        underDefended: true,
        kingPinned: false,
        pinnedBy: null,
      },
    },
    {
      alias: "black-queenside-bishop",
      ref: "piece:black:bishop:queenside",
      label: "Black queenside bishop",
      currentSquare: "c8",
      mechanicalState: "undeveloped",
      authorable: false,
      development: null,
      interrupts: [],
      relationships: {
        attacks: [], attackers: [], defendersByAttacker: [], distinctDefenders: [],
        attackerCount: 0, defenderCount: 0, attackBalance: 0,
        attacked: false, undefended: false, underDefended: false,
        kingPinned: false, pinnedBy: null,
      },
    },
  ],
  developmentOrder: ["d-pawn"],
  interruptOrder: ["d-pawn.take-bishop"],
  attempt: null,
  navigation: { canBack: false, canRestart: false },
  evaluation: { status: "off", centipawns: null, mateIn: null, message: null },
  errors: [],
};
